# Generated by Django 3.2.4 on 2022-02-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='arche.category', unique=True),
        ),
    ]
