# Generated by Django 3.2.4 on 2022-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
