# Generated by Django 3.2.4 on 2022-02-18 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom', max_length=150, unique=True)),
                ('description', models.CharField(default='Description', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('web_link', models.URLField()),
                ('image', models.ImageField(unique=True, upload_to='work_image/')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(default='Description', max_length=500)),
                ('username', models.CharField(default='None', max_length=100)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='work.works')),
            ],
        ),
    ]
