# Generated by Django 3.2.4 on 2022-02-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='web_link',
        ),
    ]
