# Generated by Django 3.2.4 on 2022-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_works_web_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.CharField(default='Description', max_length=500, null=True),
        ),
    ]
