# Generated by Django 3.2.4 on 2022-02-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_works_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='likes',
        ),
    ]
