# Generated by Django 3.2.4 on 2022-02-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
