# Generated by Django 3.2.4 on 2022-03-09 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_works_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
