# Generated by Django 3.2.4 on 2022-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20220316_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.ImageField(default='default_work.png', null=True, unique=True, upload_to='work_image/'),
        ),
    ]
